version: '3.1'

services:
  gtag-preview:
    container_name: gtag-preview
    image: gcr.io/cloud-tagging-10302018/gtm-cloud-image:stable
    restart: unless-stopped
#    mem_limit: 128M
#    cpus: '0.25'
    env_file:
      - ./gtag-preview-server.env
    ports:
      - '10101:8080'

  gtag-server:
    container_name: gtag-server
    image: gcr.io/cloud-tagging-10302018/gtm-cloud-image:stable
    restart: unless-stopped
#    mem_limit: 128M
#    cpus: '0.25'
    env_file:
      - ./gtag-server.env
    ports:
      - '10100:8080'

